// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHP3-jSXkiEFyF6VGoj-zqQxNGax1J2Ks',
    appId: '1:220134279231:web:878e5f7cb12be1ded8d08a',
    messagingSenderId: '220134279231',
    projectId: 'petpet-69ab0',
    authDomain: 'petpet-69ab0.firebaseapp.com',
    storageBucket: 'petpet-69ab0.appspot.com',
    measurementId: 'G-05ZFWNX1MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb9hMpBJzdn64AejVk4fESZMav_pr3Tck',
    appId: '1:220134279231:android:9512854e463a4c94d8d08a',
    messagingSenderId: '220134279231',
    projectId: 'petpet-69ab0',
    storageBucket: 'petpet-69ab0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiLfoXk4teCInTSkpL3vB-_fFdKp5378s',
    appId: '1:220134279231:ios:a2cc127cad18f14dd8d08a',
    messagingSenderId: '220134279231',
    projectId: 'petpet-69ab0',
    storageBucket: 'petpet-69ab0.appspot.com',
    iosBundleId: 'com.example.ouaBootcampGrup30',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiLfoXk4teCInTSkpL3vB-_fFdKp5378s',
    appId: '1:220134279231:ios:a2cc127cad18f14dd8d08a',
    messagingSenderId: '220134279231',
    projectId: 'petpet-69ab0',
    storageBucket: 'petpet-69ab0.appspot.com',
    iosBundleId: 'com.example.ouaBootcampGrup30',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHP3-jSXkiEFyF6VGoj-zqQxNGax1J2Ks',
    appId: '1:220134279231:web:609f423f7c6c092dd8d08a',
    messagingSenderId: '220134279231',
    projectId: 'petpet-69ab0',
    authDomain: 'petpet-69ab0.firebaseapp.com',
    storageBucket: 'petpet-69ab0.appspot.com',
    measurementId: 'G-WJ90Y0LYD7',
  );
}
